config/routes.rb
Popup::Application.routes.draw do
  get "users/edit"

  get "sessions/create"

  get "pages/home"
  resources :users, :only => [:edit]

  get "pages/about"
  match "/about" => "pages#about"

  get "pages/retailers"
  match "/retailers" => "pages#retailers"
  
  get "pages/contact"
  match "/contact" => "pages#contact"
  
  get "pages/merchants"
  match "/merchants" => "pages#merchants"
  
  get "pages/city"
  match "/city" => "pages#city"
  
  get "pages/welcome"
  match "/welcome" => "pages#welcome"

  resources :shares
  match "/auth/:provider/callback" => "sessions#create"
  match '/signout' => "sessions#destroy", :as => :signout
  resources :events
  root :to => 'pages#welcome'

end

app/models/event.rb
class Event < ActiveRecord::Base
mount_uploader :picture1, ImageUploader  
mount_uploader :picture2, ImageUploader 
mount_uploader :picture3, ImageUploader 
mount_uploader :picture4, ImageUploader 
mount_uploader :picture5, ImageUploader 
mount_uploader :product1, ImageUploader
mount_uploader :product2, ImageUploader

end

app/models/share.rb
class Share < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

def self.create_with_omniauth(auth)
create! do |user|
	user.facebook_id = auth["uid"]
	user.name = auth["info"]["name"]
	user.email = auth["info"]["email"]
	user.token = auth['credentials']['token'] #Store token info for later use
	
	
end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  before_filter :is_admin, :only => [:edit, :update, :new, :create, :destroy]
  def index
    @user = current_user
	if @user.nil?
		redirect_to pages_welcome_path and return
	end 
	if params[:cat].present?
    @events = Event.find_all_by_tag1_and_city(params[:cat], @user.city)
	else
	@events = Event.find_all_by_city(@user.city)
	end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :notice => 'Event was successfully created.' }
        format.json { render :json => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, :notice => 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
  def is_admin
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @events = Event.all
  end
  
  def about    
  end

  def retailers
  end 
  
  def contact
  end
  
  def merchants
  end
  
  def city
  @user = current_user
  if @user.nil?
	redirect_to pages_welcome_path and return
   end 
  end
  
  def welcome
  if current_user 
	if current_user.city?
		redirect_to '/events' and return
	else
		redirect_to pages_city_path and return
	end
  end
  render :layout=> "layoutwelcome"
  #...
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_facebook_id(auth["uid"])
	
	

	if user #Direct to Dashboard if an existing user
		session[:user_id] = user.id

	else #Direct to New Project signup if this is a new user
		user = User.create_with_omniauth(auth)
		if session[:referral]
			user.referral_source = session[:referral]
			user.save
			session[:referral] = nil
		end
		session[:user_id] = user.id
		
		flash[:success] = "Thanks for signing up for Snowball. We're anxious to hear more about you're doing!"
	end
  redirect_to '/'

end

def destroy
	session[:user_id] = nil
	redirect_to root_url, :notice => "You have signed out successfully!"
end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shares }
    end
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
    @share = Share.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @share }
    end
  end

  # GET /shares/new
  # GET /shares/new.json
  def new
    @share = Share.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @share }
    end
  end

  # GET /shares/1/edit
  def edit
    @share = Share.find(params[:id])
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(params[:share])

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, :notice => 'Share was successfully created.' }
        format.json { render :json => @share, :status => :created, :location => @share }
      else
        format.html { render :action => "new" }
        format.json { render :json => @share.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shares/1
  # PUT /shares/1.json
  def update
    @share = Share.find(params[:id])

    respond_to do |format|
      if @share.update_attributes(params[:share])
        format.html { redirect_to @share, :notice => 'Share was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @share.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share = Share.find(params[:id])
    @share.destroy

    respond_to do |format|
      format.html { redirect_to shares_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  if current_user.nil?
	redirect_to pages_welcome_path and return
  else 
	u = current_user
	u.city = params[:city]
	u.save
	redirect_to '/events' and return
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :multipart => true } do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Basic Details</h2>
  <br />
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title , :size => "25x5" %>
  </div>
  <br />
  <div class="field">
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <br />
   <div class = "field">
	 <p>City</p>
      <%= select("event", "city",["New York City", "Los Angeles", "San Francisco"]) %>
  </div>
    <br />
     <div class="field">
   <p>Category (Food, Fashion, Art)</p>
    <%= select("event", "tag1",["Food", "Fashion", "Art"]) %>
  </div>
  <br />
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description , :size => "25x5"%>
  </div>
  <hr>
    <h2>Slider Photos</h2>
      <br />
  <div class="field">
    <%= f.label :picture1 %>
    <%= f.file_field :picture1 %>
  </div>
    <br />
  <div class="field">
    <p>Share tags for picture (<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :share_1, :size => "25x5"%>
  </div>
    <br />
  <div class="field">
    <%= f.label :picture2 %>
    <%= f.file_field :picture2 %>
  </div>
  <div class="field">
    <p>Share tags for picture (<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :share_2, :size => "25x5"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :picture3 %>
    <%= f.file_field :picture3 %>
  </div>
  <div class="field">
    <p>Share tags for picture (<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :share_3, :size => "25x5"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :picture4 %>
    <%= f.file_field :picture4 %>
  </div>
  <div class="field">
    <p>Share tags for picture (<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :share_4, :size => "25x5"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :picture5 %>
    <%= f.file_field :picture5 %>
  </div>
  <div class="field">
    <p>Share tags for picture (<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :share_5, :size => "25x5"%>
  </div>
  <hr>
  <h2>
  <h2>Product Photos</h2>
  <br />
  
  <div class="field">
    <%= f.label :product1 %>
    <%= f.file_field :product1 %>
  </div>
  <div class="field">
    <%= f.label :product1_info %>
    <p>(<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :product1_info, :size => "25x5" %>
  </div>
  <br />
  <div class="field">
    <%= f.label :product2 %>
    <%= f.file_field :product2 %>
  </div>
   <div class="field">
    <%= f.label :product2_info %>
    <p>(<a href="http://pinterest.com/about/goodies/">Pinterest</a>)</p>
    <%= f.text_area :product2_info, :size => "25x5"%>
  </div>
  <br />
  <hr>   
  <h2>Highlight Boxes</h2>

  <div class="field">
    <%= f.label :start %>
    <%= f.date_select :start %>
  </div>
  <br />
  <div class="field">
    <%= f.label :end %>
    <%= f.date_select :end %>
  </div>
  <br />
  <div class="field">
    <%= f.label :open %>
    <%= f.text_area :open, :size => "25x5"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :map %>   
    <p><a href="http://maps.google.com/maps?hl=en&tab=wl&authuser=0">Website</a></p>
    <p>&output=embed<b>&iwloc=near</b></p>
    <%= f.text_area :map, :size => "25x5"%>
  </div>
  <br />
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <br />
  <div class="field">
    <%= f.label :facebook %>
    <p><a href="https://developers.facebook.com/docs/reference/plugins/like-box/">Website</a></p>
    <%= f.text_area :facebook, :size => "25x5"%>
  </div>
    <br />
  <div class="field">
  <p>Twitter embed code</p>
  <p><a href="https://twitter.com/about/resources/widgets/widget_profile">Website</a></p>
    <%= f.text_area :twitter, :size => "25x5"%>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-danger btn-large" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container" id="main-content">
<div class="row">
<div class="span12">
<div class="categorybox">

<div id="headline">
<h2>Editing event</h2>
</div>


<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

</div>
</div>
</div>
</div>

app/views/events/index.html.erb
			
		
		<div class="container" id="main-content">
			<div class="row">
				<div class="span12" id="headline">
				<h2>Discover Amazing Pop up Shops in <%= @user.city %>.</h2>
					<p>
					Hey There, we're glad you're here. Love Popup is excited to introduce you to the hottest pop up shops in your city. We're just getting started, so if there are any bugs or you have suggestions, <a href="contact">send us a note</a>. Gracias!
					</p>
					</div>
			
			<div class="headericons">
			<div class="span8">
			<ul class="nav nav-pills">
			<li><a href="/events/"><h3>ALL  <%= image_tag "allicon.png" %></h3></a></li>
			<li><a href="/events/?cat=Fashion"><h3>FASHION   <%= image_tag "fashionicon.png" %></h3></a></li>
			<li><a href="/events/?cat=Food"><h3>FOOD         <%= image_tag "foodicon.png" %></h3></a></li>
			<li><a href="/events/?cat=Art"><h3>ART           <%= image_tag "articon.png" %></h3></a></li>
			</ul>
			</div>
			</div>

					<div class="eventlist">
					<ul>
					<% @events .each do |e| %>
					
					<li><a href="/events/<%= e.id %>">
					<%= image_tag(e.picture1_url) %>
					<div class="eventtitlebox"></div>
					<span class="eventlisttitle"><%= e.title %></span>
					</a>
					</li>
					
					<% end %>
				</ul>
					
					</div>
					
				</div>
			</div>
		</div>
	

app/views/events/new.html.erb
<div class="container" id="main-content">
<div class="row">
<div class="span12">
<div class="categorybox">

<div id="headline">
<h2>New event</h2>
</div>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>
</div>
</div>
</div>

app/views/events/show.html.erb
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
		
<div class="container" id="main-content">
<div class="row">
<div class="span12">
<div class="categorybox">
<div id="headline">
<h2><%= @event.title %> </h2>
</div>
					
<div class="span6 columns">
<div id="myCarousel" class="carousel slide">

<!-- Carousel items -->
<div class="carousel-inner">

<div class="active item">
<%= @event.share_1.html_safe %>
<%= image_tag @event.picture1_url, :class=> "pull-left" %>
</div>


<% if @event.share_2.present? %>
<div class="item">
<%= @event.share_2.html_safe %>
<%= image_tag @event.picture2_url, :class=> "pull-left" %>
</div>

<% end %>

<% if @event.share_3.present? %>
<div class="item">
<%= @event.share_3.html_safe %>
<%= image_tag @event.picture3_url, :class=> "pull-left" %>
</div>
<% end %>

<% if @event.share_4.present? %>
<div class="item">
<%= @event.share_4.html_safe %>
<%= image_tag @event.picture4_url, :class=> "pull-left" %>
</div>
<% end %>

<% if @event.share_5.present? %>
<div class="item">
<%= @event.share_5.html_safe %>
<%= image_tag @event.picture5_url, :class=> "pull-left" %>
</div>
<% end %>

</div>
<!-- Carousel nav -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
</div>
 <%= @event.share_tags %> 
					<h3>About</h3>
					<p> <%= @event.description %> 
					</p>			
					<h3>When <%= image_tag "whenicon.png" %></h3>
					<p><%= @event.start %> to <%= @event.end %>
					</p>
					<h3>Open</h3>
					<p><%= @event.open %>
					</p>
				</div>
				
				
<div class="row">				

<div class="span4">
<div class="smallbox">
<h2>Shop Location  <%= image_tag "whereicon.png" %></h2>
<p><%= @event.map.html_safe %>  </p>
</div>
</div>

<div class="span4">
<div class="smallbox">
<h2>Shop Sample</h2>
<%= image_tag @event.product1_url %>
<div><%= @event.product1_info.html_safe %> </div>
</div>
</div>

<div class="span4">
<div class="smallbox">
<h2>Tweet-a-licious  <%= image_tag "birdicon.png" %></h2>
<%= @event.twitter.html_safe %>
</div>
</div>

</div>


<div class="row">	

<div class="span4">
<div class="smallbox">
<h2>Shop Sample</h2>
<%= image_tag @event.product2_url %>
<div><%= @event.product2_info.html_safe %></div>
</div>
</div>

<div class="span4">
<div class="smallbox">
<h2>Fan love  <%= image_tag "hearticon.png" %></h2>
<p>Fans galore!</p>
<div><%= @event.facebook.html_safe %> </div>
</div>
</div>

<div class="span4">
<div class="smallbox">
<h2>Want to go?</h2>
<p>Share this pop-up shop with your friends!</p>
</div>
</div>

        </div>
		</div>		
		</div>
		</div>
		</div>
		<script>$('.carousel').carousel()</script>
		
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Love Popup</title>
  <%= stylesheet_link_tag    "style.css"%>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tags %>
  <!DOCTYPE html>
		<meta charset="utf-8">
		<title>Bootstrap Business</title>
		<script>require jquery </script>
		<script> require jquery_ujs </script>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">	
		<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
	<link rel="icon" type="image/jpg" href="http://popupweekly.com/img/icon.png">
	

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>

	<body>
		<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=122628081204967";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
		<header>
			<div class="container">
				<div class="row">
					<h1 id="logo" class="span4"><a href="/" title="Business"><span class="red">LOVE</span><%= image_tag "heart.png" , :style=>"margin-bottom:-10px; margin-right:-2px" %>POPUP</a><%= image_tag "beta.png" , :style=>"margin-top:5px" %></h1>

<div id="row">
<div id="rightclass">
<nav class="span8" id="navigation">
<ul class="nav pull-right">
<li id="fat-menu" class="dropdown">
<% if @current_user.present?  %>	
<a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome <%= @current_user.name.split(" ").first %>
<b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a href="/city.html">Change City</a></li>
<li><%= link_to "Logout", signout_path %></li>
<li class="divider"></li>
<% end %>
</ul>
</li>
</ul>
</nav>
</div>
</div>

				</div>
			</div>
			</header>
			
		<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32103813-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>

<%= yield %>
<footer>
			<div class="container">
				<div class="row">
				<div class="span4">
						<h4>Learn More About Us</h4>
						<ul class="unstyled">
							<li><a href="about">About</a></li>
							<li><a href="merchants">Merchants</a></li>
							<li><a href="retailers">Retailers</a></li>
							<li><a href="http://www.popupweekly.com/">Blog</a></li>
							<li><a href="contact">Contact</a></li>

						</ul>
					</div>
					<div class="span4">
						<h4>Connect With Us</h4>
						<ul class="unstyled">
							<li><a href="http://pinterest.com/lovepopup/">Pinterest</a></li>
							<li><a href="https://www.facebook.com/pages/Popup-Weekly/334564433266070">Facebook</a></li>
							<li><a href="https://twitter.com/lovepopup">Twitter</a></li>
							<li><a href="https://plus.google.com/109671987086813263137">Google+</a></li>
							<li><a href="http://www.popupweekly.com/">Blog</a></li>
						</ul>
					</div>
					<div class="span4">
						<h4>Tweet, tweet</h4>
							<script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 2,
  interval: 30000,
  width: 250,
  height: 200,
  theme: {
    shell: {
      background: 'transparent',
      color: '#faf5fa'
    },
    tweets: {
      background: '#transparent',
      color: '#ffffff',
      links: '#f07773'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    behavior: 'all'
  }
}).render().setUser('LovePopup').start();

</script>
					</div>
				</div>
			</div>
		</footer>
</body>
</html>

app/views/layouts/layoutwelcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Love Popup</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!DOCTYPE html>
		<meta charset="utf-8">
		<title>Bootstrap Business</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">	
		<link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
		<script src="js/bootstrap-carousel.js" ></script> 

	<link rel="icon" type="image/jpg" href="http://popupweekly.com/img/icon.png">
	

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>

	<body>
		
		<header>
			<div class="container">
				<div class="row">
					<h1 id="logo" class="span4"><a href="/" title="Business"><span class="red">LOVE</span><%= image_tag "heart.png" %>POPUP</a></h1>
				</div>
			</div>
			<meta name="google-site-verification" content="XOUNIH7-zfFQjtLmYUx6AXaxHksLn_qq-5qmTyAzjfo" />
			</header>
</head>
<body>

<%= yield %>
<footer>
			<div class="container">
				<div class="row">
				<div class="span4">
						<h4>Learn More About Us</h4>
						<ul class="unstyled">
							<li><a href="about">About</a></li>
							<li><a href="merchants">Merchants</a></li>
							<li><a href="retailers">Retailers</a></li>
							<li><a href="http://www.popupweekly.com/">Blog</a></li>
							<li><a href="contact">Contact</a></li>

						</ul>
					</div>
					<div class="span4">
						<h4>Connect With Us</h4>
						<ul class="unstyled">
							<li><a href="http://pinterest.com/lovepopup/">Pinterest</a></li>
							<li><a href="http://www.facebook.com/lovepopupshops">Facebook</a></li>
							<li><a href="http://twitter.com/lovepopup">Twitter</a></li>
							<li><a href="http://plus.google.com/b/109671987086813263137/109671987086813263137/posts">Google+</a></li>
							<li><a href="http://www.popupweekly.com/">Blog</a></li>
						</ul>
					</div>
					<div class="span4">
						<h4>Like us On Facebook</h4>
							<ul class="unstyled">
<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Flovepopupshops&amp;send=false&amp;layout=standard&amp;width=350&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=80&amp;appId=185906091473461" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:350px; height:80px;" allowTransparency="true"></iframe>
</ul>
					</div>
				</div>
			</div>
		</footer>
</body>
</html>

app/views/pages/city.html.erb
<div class="container" id="main-content">
<div class="row">
<div class="span12">

<div id="headline">
<h2>Hello <%= @current_user.name.split(" ").first %>! Select your city:</h2>
<br/>
<p>At the heart of Love Popup is our passion to help you discover great shopping experiences.</p><p>Don't see your city?  Please <a href="contact">reach out</a> to us, or consider becoming a <a href="ambassador">Love Popup Ambassador!</a>
</p> 
</div>
					
<div class="citylist">
<ul>
<li>
<%= link_to image_tag("nyc.jpg"), edit_user_path(@user, :city => "New York City") %>
<span class="citylisttitle"><a><%= link_to "New York" , edit_user_path(@user, :city => "New York City") %></a></span>
</li>

<li>
<%= link_to image_tag("la.jpg"), edit_user_path(@user, :city => "Los Angeles") %>
<span class="citylisttitle"><a><%= link_to "Los Angeles" , edit_user_path(@user, :city => "Los Angeles") %></a></span>
</li>

<li>
<%= link_to image_tag("sanfrancisco.jpg"), edit_user_path(@user, :city => "San Francisco") %>
<div class="citylisttitle"><%= link_to "San Francisco" , edit_user_path(@user, :city => "San Francisco") %></div>
</li>

<li>
<%= link_to image_tag("boston.jpg"), edit_user_path(@user, :city => "Boston") %>
<div class="citylisttitle"><%= link_to "Boston" , edit_user_path(@user, :city => "Boston") %></div>
</li>


</ul>

</div>
</div>



</div>
</div>

<div class="cityspace"></div>

		
	

app/views/shares/edit.html.erb
<h1>Editing share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<h1>Listing shares</h1>

<table>
  <tr>
    <th>User</th>
    <th>Offer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shares.each do |share| %>
  <tr>
    <td><%= share.user_id %></td>
    <td><%= share.offer_id %></td>
    <td><%= link_to 'Show', share %></td>
    <td><%= link_to 'Edit', edit_share_path(share) %></td>
    <td><%= link_to 'Destroy', share, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New share</h1>

<%= render 'form' %>

<%= link_to 'Back', shares_path %>

app/views/shares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @share.user_id %>
</p>

<p>
  <b>Offer:</b>
  <%= @share.offer_id %>
</p>


<%= link_to 'Edit', edit_share_path(@share) %> |
<%= link_to 'Back', shares_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>